---
configure_dotfiles: false
configure_terminal: false
configure_osx: false

# Set to 'true' to configure the Dock via dockutil.
configure_dock: true
dockitems_remove:
  - TV
  - Podcasts
dockitems_persist:
  - name: "Launchpad"
    path: "/Applications/Launchpad.app"
    pos: 1
  - name: "Google Chrome"
    path: "/Applications/Google Chrome.app"
    pos: 2
  - name: "Safari"
    path: "/Applications/Safari.app"
    pos: 3
  - name: "CotEditor"
    path: "/Applications/CotEditor.app"
    pos: 4
  - name: "WezTerm"
    path: "/Applications/WezTerm.app"
    pos: 5
  - name: "GitKraken"
    path: "/Applications/GitKraken.app/"
    pos: 6
  - name: "Microsoft Word"
    path: "/Applications/Microsoft Word.app/"
    pos: 7
  - name: "Microsoft Excel"
    path: "/Applications/Microsoft Excel.app/"
    pos: 8
# - name: "Sublime Text"
#   path: "/Applications/Sublime Text.app/"
#   pos: 5

configure_sudoers: false
sudoers_custom_config: ''
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

dotfiles_repo: https://github.com/wstalsma/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/dotfiles
dotfiles_files: []

homebrew_installed_packages: 
  #- ansible # Must be first installed via Pip.
  - atuin
  - ca-certificates
  - certifi
  - cffi
  - cryptography
  - cowsay
  - dockutil
  - eza
  - gettext
  - git
  - go
  - iperf
  - libgit2
  - libsodium
  - libssh
  - libssh2
  - libunistring
  - libuv
  - libvterm
  - libyaml
  - lpeg
  - luajit
  - luv
  - mpdecimal
  - msgpack
  - neovim
  - node
  - oh-my-posh
  - openssl@3
  - pandoc
  - pcre2
  - podman
  - powerlevel10k
  - putty
  - pycparser
  - python@3.13
  - readline
  - sevenzip
  - sqlite
  - sshpass
  - stow
  - tree-sitter
  - unibilium
  - xz
  - yazi
  - zoxide
  - zsh-autosuggestions
  - zsh-syntax-highlighting

homebrew_taps: []

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - arduino-ide
  - elgato-camera-hub
  - elgato-control-center
  - elgato-stream-deck
  - firefox
  - font-meslo-lg-nerd-font
  - jordanbaird-ice
  - microsoft-auto-update
  - microsoft-office
  - podman-desktop
  - powershell
  - visual-studio-code
  - wezterm

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Set to 'true' to configure Sublime Text.
configure_sublime: false
sublime_base_path: '~/Library/Application Support/Sublime Text'
sublime_config_path: "Packages/User"
sublime_package_control:
  - "DocBlockr"
  - "Dockerfile Syntax Highlighting"
  - "FileDiffs"
  - "GitHub Flavored Markdown Preview"
  - "Jinja2"
  - "Package Control"
  - "PHP-Twig"
  - "Pretty JSON"
  - "SublimeLinter"
  - "SublimeLinter-contrib-yamllint"
  - "TrailingSpaces"
  - "WordCount"

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []